[versions]
agp = "8.9.1"
annotation = "1.9.1"
lsparanoid = "0.6.0"
kotlin = "2.1.20"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
lsplugin-publish = { id = "org.lsposed.lsplugin.publish", version = "1.1" }
agp = { id = "com.android.application", version.ref = "agp" }
lsparanoid = { id = "org.lsposed.lsparanoid", version = "0.6.0" }

[libraries]
agp-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lsparanoid-core = { group = "org.lsposed.lsparanoid", name = "core", version.ref = "lsparanoid" }
grip = { group = "com.joom.grip", name = "grip", version = "0.9.1" }
asm-common = { group = "org.ow2.asm", name = "asm-commons", version = "9.8" }
kotlin-api = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin-api", version.ref = "kotlin" }
